### ISSUE TITLE
Hacking/Pentest

### ISSUE THREAD

**Issue by erikalopes** [GabrielCMarinho/Links-uteis#82]
Olá, olhei os titulos de pentest, e achei que seria útil adicionar links
de eventos de CTF's desde os níveis iniciantes até os mais avançados, que é uma 
ótima ferramenta pra quem tá iniciando em segurança da informação.

Então criei a issue para tirar essa dúvida, pode add links nesses estilos?

**Comment by GabrielCMarinho** [comment]
Sem dúvidas que sim, Erika! Fico no aguardo da sua PR. :)

**Comment by erikalopes** [comment]
Obrigada! Indo contribuir agora...
